### PR TITLE
Initial app UI

### PR DESCRIPTION
**Pull request by Pedanticc**

### CODE REVIEW

**Comment by unexploredtest** [comment]
Okay, I went on and made the desired changes. There remain a few bugs, but I think we can merge it for now and open issues for the said bugs and deal with them later on. What do you think @Pedanticc ? Also is there something else you want to add?

**Comment by Pedanticc** [comment]
Things look smooth for now. Maybe I'll remove the `**Save Graph**` button and add it once there is graph to be saved.

**Comment by Pedanticc** [comment]
Things look smooth for now. Maybe I'll remove the `Save Graph` button and add it once there is graph to be saved.

**Comment by Pedanticc** [comment]
Things look smooth for now. Maybe I'll remove the `Save Graph` button and add it once there is graph to be saved.
By the way, @unexploredtest , what do you think about a page load animation?

**Comment by Pedanticc** [comment]
Things look smooth for now. Maybe I'll remove the Save Graph button and add it once there is graph to be saved.
By the way, what do you think about a page load animation?

**Comment by Pedanticc** [comment]
Things look smooth for now. Maybe I'll remove the `Save Graph` button and add it once there is graph to be saved.
By the way, what do you think about a page load animation?

**Comment by unexploredtest** [comment]
> By the way, what do you think about a page load animation?

Would be a great addition!

**Comment by unexploredtest** [comment]
There are still some issues remaining, but I think they're not too major and can post pone them. I'll merge it for now.

**Pull request merged**
